oneup_uploader:
    mappings:
        local_tmp:
            frontend: blueimp
            max_size: 137438953472 # 128M
            storage:
                type: filesystem
                directory: "%kernel.data_dir%/tmp"
